### PR TITLE
feat(CD): add success field to /job-status/

### LINKED ISSUE #5: [BUG] finished status instead of error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When unreachable on ansible result.  the json return 'finished' instead of 'error'

```
Friday 05 May 2023  15:06:47 +0000 (0:00:00.041)       0:00:00.041 ************ 
fatal: [***]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nPermissions 0664 for '/root/.ssh/id_ed25519' are too open.\r\nIt is required that your private key files are NOT accessible by others.\r\nThis private key will be ignored.\r\nLoad key \"/root/.ssh/id_ed25519\": bad permissions\r\nroot@***: Permission denied (publickey,password).", "unreachable": true}

PLAY RECAP *********************************************************************
***     : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

Friday 05 May 2023  15:06:48 +0000 (0:00:00.099)       0:00:00.141 ************ 
=============================================================================== 
Gathering Facts --------------------------------------------------------- 0.10s
Process return code: 4
Deployment finished!
```

### Expected Behavior

We should have an error, so we can return an exit code of 1;

### Steps To Reproduce

_No response_

### Environment

```Markdown
- OS:
- Node:
- npm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sbancal**
FIX https://github.com/EPFL-ENAC/enac-cd-app/issues/5

In case of success, returns:
```json
{
    "job_id": "01GZY1VPYBYV4S28P7YHXSP0RE",
    "output": "",
    "status": "success"
}
```

In case of any error (unreachable/failure/...):
```json
{
    "job_id": "01GZY1HF06R50ZJRKK83R4QXA4",
    "output": "",
    "status": "error"
}
```

### CODE REVIEW

**Comment by guilbep** [comment]
So @sbancal Right now the github actions is behaving like we agreed:

'finished' means successful
'error' means failure

I don't think adding a new field is good idea; it adds complexity when we already have a solution

**Review by guilbep — CHANGES_REQUESTED** [review]
I'd prefer if we keep the already existing status finished/error

Why should we have a new field ?

**Comment by sbancal** [comment]
I've merged for you the 2 informations into one field.
Now "status" can be either `"success"` or `"error"`, when the app-deploy is finished.
I let you check https://github.com/EPFL-ENAC/epfl-enac-deploy-action/issues/8
thks

**Comment by guilbep** [comment]
@sbancal I don't have time anymore; So I'll let you do a pull request on epfl-enac-deploy-action to change 'finished' in 'success'

**Pull request merged**
